import type { CharterErrorCode } from '../contracts/errors.ts';
import type { TaskContract } from '../contracts/task-contract.ts';

export const ROOT = '/projects/fixture';

/** Positive fixtures: shape-complete contracts that MUST be accepted. */
export const POSITIVE_CONTRACTS: { name: string; contract: TaskContract }[] = [
  {
    // Spec §11 canonical shape.
    name: 'critical correction',
    contract: {
      version: 'charter/v0.1',
      task: { id: 'example-task', class: 'T3', risk: 'critical' },
      role: 'correct',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master', 'reviewer-findings'] },
      scope: { blockers: ['blocker-a'], files: ['internal/example.go', 'internal/example_test.go'] },
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: {
        commands: ['go test ./...', 'go vet ./...'],
        assertions: ['blocker-a-eliminated', 'no-release-changes'],
        review: { required: true, independence: 'none', executor: 'same_session' },
      },
      verification: { level: 'V3' },
      limits: { correction_rounds: 2, semantic_escalations: 1 },
      non_goals: ['architecture redesign', 'unrelated refactor'],
    },
  },
  {
    name: 'read-only review',
    contract: {
      version: 'charter/v0.1',
      task: { id: 'review-bounded-change', class: 'T1', risk: 'medium' },
      role: 'review',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['reviewer-findings'] },
      scope: { files: ['internal/example.go'] },
      permissions: { code_write: false, research: false, external_write: false, release: false },
      acceptance: { assertions: ['findings-reported'] },
      verification: { level: 'V3' },
    },
  },
  {
    name: 'planner decomposition (no mutation)',
    contract: {
      version: 'charter/v0.1',
      task: { id: 'decompose-frozen-work', class: 'T2', risk: 'medium' },
      role: 'planner',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: {},
      permissions: { code_write: false, research: false, external_write: false, release: false },
      acceptance: { assertions: ['work-units-bounded'] },
      verification: { level: 'V1' },
      limits: { semantic_escalations: 1 },
    },
  },
  {
    name: 'subagents implement with independent review',
    contract: {
      version: 'charter/v0.1',
      task: { id: 'bounded-implementation', class: 'T1', risk: 'low' },
      role: 'implement',
      execution_target: 'subagents',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { files: ['src/feature.ts'], directories: ['src/feature'] },
      permissions: { code_write: true, research: true, external_write: false, release: false },
      acceptance: {
        commands: ['npm test'],
        review: { required: true, independence: 'independent', executor: 'fresh_session' },
      },
      verification: { level: 'V2' },
      limits: { correction_rounds: 1 },
    },
  },
  {
    name: 'unrestricted scope admitted by explicit override',
    contract: {
      version: 'charter/v0.1',
      task: { id: 'repository-wide-lint-fix', class: 'T2', risk: 'high' },
      role: 'correct',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { files: ['**/*'], allow_unrestricted: true },
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: { commands: ['npm run lint'], assertions: ['lint-clean'] },
      verification: { level: 'V2' },
    },
  },
  {
    name: 'adjudicate evidence-backed architecture conflict',
    contract: {
      version: 'charter/v0.1',
      task: { id: 'resolve-architecture-conflict', class: 'T4', risk: 'critical', evidence: ['conflict-report-7'] },
      role: 'adjudicate',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { sections: ['3. Product Boundary'] },
      permissions: { code_write: false, research: false, external_write: false, release: false },
      acceptance: { assertions: ['decision-frozen'], review: { required: false, independence: 'none' } },
      verification: { level: 'V0' },
      limits: { semantic_escalations: 1 },
    },
  },
  {
    name: 'release action with release explicitly admitted',
    contract: {
      version: 'charter/v0.1',
      task: { id: 'tag-admitted-release', class: 'T2', risk: 'high' },
      role: 'implement',
      execution_target: 'subagents',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { files: ['release/manifest.json'] },
      permissions: { code_write: true, research: false, external_write: true, release: true },
      acceptance: { commands: ['npm run release:verify'], assertions: ['manifest-consistent'] },
      verification: { level: 'V5' },
      actions: ['tag'],
    },
  },
];

/** Negative fixtures: shape-complete contracts that MUST fail closed with the exact expected codes, in order. */
export const NEGATIVE_CONTRACTS: {
  name: string;
  contract: unknown;
  expected: CharterErrorCode[];
  ambiguousBinder?: boolean;
}[] = [
  // ── E2 role/task/permission conflict ──────────────────────────────────────
  {
    name: 'E2 review role with code_write=true',
    expected: ['INVALID_TASK_CONTRACT'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'conflicting-review', class: 'T1', risk: 'medium' },
      role: 'review',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { files: ['internal/example.go'] },
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: { assertions: ['findings-reported'] },
      verification: { level: 'V1' },
    },
  },
  {
    name: 'E2 planner role with code_write=true',
    expected: ['INVALID_TASK_CONTRACT'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'planner-code-write', class: 'T2', risk: 'medium' },
      role: 'planner',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { files: ['src/feature.ts'] },
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: { assertions: ['plan-ready'] },
      verification: { level: 'V1' },
    },
  },
  {
    name: 'E2 planner role with external_write=true',
    expected: ['INVALID_TASK_CONTRACT'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'planner-external-write', class: 'T2', risk: 'medium' },
      role: 'planner',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: {},
      permissions: { code_write: false, research: false, external_write: true, release: false },
      acceptance: { assertions: ['plan-ready'] },
      verification: { level: 'V1' },
    },
  },
  {
    name: 'E2 planner role with release=true',
    expected: ['INVALID_TASK_CONTRACT'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'planner-release', class: 'T2', risk: 'medium' },
      role: 'planner',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: {},
      permissions: { code_write: false, research: false, external_write: false, release: true },
      acceptance: { assertions: ['plan-ready'] },
      verification: { level: 'V1' },
    },
  },
  {
    name: 'E2 T4 without evidence',
    expected: ['INVALID_TASK_CONTRACT'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 't4-unevidenced', class: 'T4', risk: 'critical' },
      role: 'adjudicate',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { sections: ['3. Product Boundary'] },
      permissions: { code_write: false, research: false, external_write: false, release: false },
      acceptance: { assertions: ['decision-frozen'] },
      verification: { level: 'V0' },
    },
  },
  // ── E3 authority unresolved ───────────────────────────────────────────────
  {
    name: 'E3 unknown authority reference',
    expected: ['AUTHORITY_UNRESOLVED'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'unknown-authority', class: 'T1', risk: 'medium' },
      role: 'implement',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master-v9-draft'] },
      scope: { files: ['src/feature.ts'] },
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: { assertions: ['feature-implemented'] },
      verification: { level: 'V1' },
    },
  },
  {
    name: 'E3 ambiguous authority reference',
    expected: ['AUTHORITY_UNRESOLVED'],
    ambiguousBinder: true,
    contract: {
      version: 'charter/v0.1',
      task: { id: 'ambiguous-authority', class: 'T1', risk: 'medium' },
      role: 'implement',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { files: ['src/feature.ts'] },
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: { assertions: ['feature-implemented'] },
      verification: { level: 'V1' },
    },
  },
  {
    name: 'E3 one of two references unresolved',
    expected: ['AUTHORITY_UNRESOLVED'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'partially-resolved-authority', class: 'T1', risk: 'medium' },
      role: 'implement',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master', 'unbound-findings'] },
      scope: { files: ['src/feature.ts'] },
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: { assertions: ['feature-implemented'] },
      verification: { level: 'V1' },
    },
  },
  // ── E4 invalid or overbroad scope ─────────────────────────────────────────
  {
    name: 'E4 bounded write role with empty scope',
    expected: ['INVALID_TASK_CONTRACT'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'empty-scope-correction', class: 'T1', risk: 'medium' },
      role: 'correct',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: {},
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: { assertions: ['finding-applied'] },
      verification: { level: 'V1' },
    },
  },
  {
    name: 'E4 unrestricted scope without explicit override',
    expected: ['CONTRACT_REQUIRES_EXPLICIT_OVERRIDE'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'unbounded-correction', class: 'T1', risk: 'medium' },
      role: 'correct',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { files: ['**/*'] },
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: { assertions: ['finding-applied'] },
      verification: { level: 'V1' },
    },
  },
  {
    name: 'E4 scope entry escaping root',
    expected: ['SCOPE_CONTRADICTION'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'escaping-scope', class: 'T1', risk: 'medium' },
      role: 'implement',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { files: ['../sibling-project/file.ts'] },
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: { assertions: ['feature-implemented'] },
      verification: { level: 'V1' },
    },
  },
  {
    name: 'E4 absolute scope entry',
    expected: ['SCOPE_CONTRADICTION'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'absolute-scope', class: 'T1', risk: 'medium' },
      role: 'implement',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { files: ['/etc/hosts'] },
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: { assertions: ['feature-implemented'] },
      verification: { level: 'V1' },
    },
  },
  // ── E5 unverifiable acceptance ────────────────────────────────────────────
  {
    name: 'E5 fuzzy command acceptance',
    expected: ['ACCEPTANCE_INVALID'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'fuzzy-command', class: 'T1', risk: 'medium' },
      role: 'implement',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { files: ['src/feature.ts'] },
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: { commands: ['make production ready'] },
      verification: { level: 'V1' },
    },
  },
  {
    name: 'E5 fuzzy assertion acceptance',
    expected: ['ACCEPTANCE_INVALID'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'fuzzy-assertion', class: 'T1', risk: 'medium' },
      role: 'implement',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { files: ['src/feature.ts'] },
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: { assertions: ['ensure architecture is good'] },
      verification: { level: 'V1' },
    },
  },
  {
    name: 'E5 fuzzy single-token assertion',
    expected: ['ACCEPTANCE_INVALID'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'fuzzy-token-assertion', class: 'T1', risk: 'medium' },
      role: 'implement',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { files: ['src/feature.ts'] },
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: { assertions: ['production_ready'] },
      verification: { level: 'V1' },
    },
  },
  {
    name: 'E5 empty acceptance',
    expected: ['ACCEPTANCE_INVALID'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'empty-acceptance', class: 'T1', risk: 'medium' },
      role: 'implement',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { files: ['src/feature.ts'] },
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: {},
      verification: { level: 'V1' },
    },
  },
  // ── E7 forbidden structured action ────────────────────────────────────────
  {
    name: 'E7 release=false with tag action',
    expected: ['CONTRACT_CONTRADICTION'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'forbidden-tag', class: 'T1', risk: 'medium' },
      role: 'implement',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { files: ['src/feature.ts'] },
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: { assertions: ['feature-implemented'] },
      verification: { level: 'V1' },
      actions: ['tag'],
    },
  },
  {
    name: 'E7 release=false with tag and publish actions',
    expected: ['CONTRACT_CONTRADICTION'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'forbidden-publish', class: 'T1', risk: 'medium' },
      role: 'implement',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { files: ['src/feature.ts'] },
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: { assertions: ['feature-implemented'] },
      verification: { level: 'V1' },
      actions: ['tag', 'publish'],
    },
  },
  {
    name: 'E7 external_write=false with push action',
    expected: ['CONTRACT_CONTRADICTION'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'forbidden-push', class: 'T1', risk: 'medium' },
      role: 'implement',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { files: ['src/feature.ts'] },
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: { assertions: ['feature-implemented'] },
      verification: { level: 'V1' },
      actions: ['push'],
    },
  },
  // ── Review independence truthfulness (spec §4.3, §26.1) ───────────────────
  {
    name: 'same-session review claimed independent',
    expected: ['CONTRACT_CONTRADICTION'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'fake-independence', class: 'T2', risk: 'high' },
      role: 'review',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { files: ['src/feature.ts'] },
      permissions: { code_write: false, research: false, external_write: false, release: false },
      acceptance: { review: { required: true, independence: 'independent', executor: 'same_session' } },
      verification: { level: 'V3' },
    },
  },
  // ── Structural ────────────────────────────────────────────────────────────
  { name: 'structural: not an object', expected: ['INVALID_TASK_CONTRACT'], contract: null },
  { name: 'structural: empty object', expected: ['INVALID_TASK_CONTRACT'], contract: {} },
  {
    name: 'structural: wrong version',
    expected: ['INVALID_TASK_CONTRACT'],
    contract: {
      version: 'charter/v0.2',
      task: { id: 'wrong-version', class: 'T1', risk: 'low' },
      role: 'implement',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { files: ['src/feature.ts'] },
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: { assertions: ['feature-implemented'] },
      verification: { level: 'V1' },
    },
  },
  {
    name: 'structural: unknown role',
    expected: ['INVALID_TASK_CONTRACT'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'unknown-role', class: 'T1', risk: 'low' },
      role: 'architect',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { files: ['src/feature.ts'] },
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: { assertions: ['feature-implemented'] },
      verification: { level: 'V1' },
    },
  },
  {
    name: 'structural: relative root',
    expected: ['INVALID_TASK_CONTRACT'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'relative-root', class: 'T1', risk: 'low' },
      role: 'implement',
      execution_target: 'parent',
      root: 'relative/project',
      authority: { sources: ['canonical-master'] },
      scope: { files: ['src/feature.ts'] },
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: { assertions: ['feature-implemented'] },
      verification: { level: 'V1' },
    },
  },
  {
    name: 'structural: empty authority sources',
    expected: ['INVALID_TASK_CONTRACT'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'no-authority', class: 'T1', risk: 'low' },
      role: 'implement',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: [] },
      scope: { files: ['src/feature.ts'] },
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: { assertions: ['feature-implemented'] },
      verification: { level: 'V1' },
    },
  },
  {
    name: 'structural: unknown structured action',
    expected: ['INVALID_TASK_CONTRACT'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'unknown-action', class: 'T1', risk: 'low' },
      role: 'implement',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { files: ['src/feature.ts'] },
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: { assertions: ['feature-implemented'] },
      verification: { level: 'V1' },
      actions: ['refactor-everything'],
    },
  },
  {
    name: 'structural: negative limits',
    expected: ['INVALID_TASK_CONTRACT'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'negative-limits', class: 'T1', risk: 'low' },
      role: 'implement',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { files: ['src/feature.ts'] },
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: { assertions: ['feature-implemented'] },
      verification: { level: 'V1' },
      limits: { correction_rounds: -1, semantic_escalations: 1.5 },
    },
  },
  {
    name: 'structural: missing permissions',
    expected: ['INVALID_TASK_CONTRACT'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'missing-permissions', class: 'T1', risk: 'low' },
      role: 'implement',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { files: ['src/feature.ts'] },
      permissions: { code_write: true },
      acceptance: { assertions: ['feature-implemented'] },
      verification: { level: 'V1' },
    },
  },
  // ── Structural: unknown fields in closed objects (Finding 1) ──────────────
  {
    name: 'structural: top-level unbounded_mode',
    expected: ['INVALID_TASK_CONTRACT'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'unbounded-top-level', class: 'T1', risk: 'low' },
      role: 'implement',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { files: ['src/feature.ts'] },
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: { assertions: ['feature-implemented'] },
      verification: { level: 'V1' },
      unbounded_mode: true,
    },
  },
  {
    name: 'structural: permissions.deploy unknown field',
    expected: ['INVALID_TASK_CONTRACT'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'unknown-permission', class: 'T1', risk: 'low' },
      role: 'implement',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { files: ['src/feature.ts'] },
      permissions: { code_write: true, research: false, external_write: false, release: false, deploy: true },
      acceptance: { assertions: ['feature-implemented'] },
      verification: { level: 'V1' },
    },
  },
  {
    name: 'structural: scope.everything unknown field',
    expected: ['INVALID_TASK_CONTRACT'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'unknown-scope', class: 'T1', risk: 'low' },
      role: 'implement',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { files: ['src/feature.ts'], everything: true },
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: { assertions: ['feature-implemented'] },
      verification: { level: 'V1' },
    },
  },
  {
    name: 'structural: authority.precedence unknown field',
    expected: ['INVALID_TASK_CONTRACT'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'unknown-authority-field', class: 'T1', risk: 'low' },
      role: 'implement',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'], precedence: 'spec' },
      scope: { files: ['src/feature.ts'] },
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: { assertions: ['feature-implemented'] },
      verification: { level: 'V1' },
    },
  },
  {
    name: 'structural: acceptance.magic unknown field',
    expected: ['INVALID_TASK_CONTRACT'],
    contract: {
      version: 'charter/v0.1',
      task: { id: 'unknown-acceptance-field', class: 'T1', risk: 'low' },
      role: 'implement',
      execution_target: 'parent',
      root: ROOT,
      authority: { sources: ['canonical-master'] },
      scope: { files: ['src/feature.ts'] },
      permissions: { code_write: true, research: false, external_write: false, release: false },
      acceptance: { assertions: ['feature-implemented'], magic: true },
      verification: { level: 'V1' },
    },
  },
];
